/*******************************************************************************
 * Copyright (c) 2009, 2026 Mountainminds GmbH & Co. KG and Contributors
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *    Evgeny Mandrikov - initial API and implementation
 *
 *******************************************************************************/
package org.jacoco.core.test.validation.java5;

import org.jacoco.core.test.validation.JavaVersion;
import org.jacoco.core.test.validation.Source.Line;
import org.jacoco.core.test.validation.ValidationTestBase;
import org.jacoco.core.test.validation.java5.targets.EnumSwitchTarget;
import org.junit.Test;

/**
 * Test of filtering of a synthetic class that is generated by javac for an enum
 * in switch statement.
 */
public class EnumSwitchTest extends ValidationTestBase {

	public EnumSwitchTest() {
		super(EnumSwitchTarget.class);
	}

	public void assertSwitch(final Line line) {
		if (isJDKCompiler && JavaVersion.current().isBefore("1.6")) {
			// class that holds "switch map" is not marked as synthetic when
			// compiling with javac 1.5
			assertPartlyCovered(line, 0, 2);
		} else {
			assertFullyCovered(line, 0, 2);
		}
	}

	@Test
	public void bytecodeSnapshots() throws Exception {
		if (!isJDKCompiler) {
			assertSnapshot(EnumSwitchTarget.class, "example",
					"ecj/example.txt");
			assertSnapshot(EnumSwitchTarget.class,
					"$SWITCH_TABLE$org$jacoco$core$test$validation$java5$targets$EnumSwitchTarget$E",
					"ecj/switch_table.txt");
		} else if (JavaVersion.current().isBefore("21")) {
			assertSnapshot(EnumSwitchTarget.class, "example",
					"5-20/example.txt");
			assertSnapshot(
					Class.forName(EnumSwitchTarget.class.getName() + "$1"),
					"<clinit>",
					(JavaVersion.current().isBefore("7") ? "5-6/" : "7-20/")
							+ "clinit.txt");
		} else {
			// https://bugs.openjdk.org/browse/JDK-7176515
			// https://github.com/openjdk/jdk/commit/ac6af6a64099c182e982a0a718bc1b780cef616e
			assertSnapshot(EnumSwitchTarget.class, "example", "example.txt");
		}
	}

}
