/*******************************************************************************
 * Copyright (c) 2009, 2026 Mountainminds GmbH & Co. KG and Contributors
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *    Evgeny Mandrikov - initial API and implementation
 *
 *******************************************************************************/
package org.jacoco.core.internal.analysis.filter;

import org.junit.Test;

/**
 * Unit tests for {@link KotlinUnsafeCastOperatorFilter}.
 */
public class KotlinUnsafeCastOperatorFilterTest extends FilterTestBase {

	private final KotlinUnsafeCastOperatorFilter filter = new KotlinUnsafeCastOperatorFilter();

	@Test
	public void should_filter() throws Exception {
		assertSnapshot(filter,
				"snapshots/KotlinUnsafeCastOperatorTarget/1.3/unsafe_cast_operator.txt");
	}

	@Test
	public void should_filter_Kotlin_1_4() throws Exception {
		assertSnapshot(filter,
				"snapshots/KotlinUnsafeCastOperatorTarget/1.4/unsafe_cast_operator.txt");
	}

	/**
	 * For
	 *
	 * <pre>
	 *   fun f(s: String?): String {
	 * 	   return s as String
	 *   }
	 * </pre>
	 *
	 * bytecode generated by Kotlin compiler version 1.4 is different from
	 * bytecode generated by version 1.5, unfortunately bytecode generated by
	 * later is the same as bytecode that both versions generate for
	 *
	 * <pre>
	 *   fun f(s: String?): String {
	 *     if (s == null)
	 *       throw NullPointerException("null cannot be cast to non-null type kotlin.String")
	 *     return s
	 *   }
	 * </pre>
	 */
	@Test
	public void should_filter_Kotlin_1_5() throws Exception {
		assertSnapshot(filter,
				"snapshots/KotlinUnsafeCastOperatorTarget/1.5/unsafe_cast_operator.txt");
	}

	@Test
	public void should_filter_Kotlin_1_6() throws Exception {
		assertSnapshot(filter,
				"snapshots/KotlinUnsafeCastOperatorTarget/1.6/unsafe_cast_operator.txt");
	}

}
